version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: file-helper-php
    image: file-helper-php
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
